// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: donation_messages.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"sakucita/internal/domain"
)

const createDonationMessage = `-- name: CreateDonationMessage :one
INSERT INTO donation_messages (
  id,
  payee_user_id,
  payer_user_id,
  payer_name,
  email,
  message,
  media_type,
  media_url,
  media_start_seconds,
  charged_seconds,
  price_per_second,
  played_at,
  amount,
  currency,
  meta
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, payee_user_id, payer_user_id, payer_name, email, message, media_type, media_url, media_start_seconds, charged_seconds, price_per_second, amount, currency, status, meta, played_at, created_at
`

type CreateDonationMessageParams struct {
	ID                uuid.UUID
	PayeeUserID       uuid.UUID
	PayerUserID       pgtype.UUID
	PayerName         string
	Email             pgtype.Text
	Message           pgtype.Text
	MediaType         DonationMediaType
	MediaUrl          pgtype.Text
	MediaStartSeconds int32
	ChargedSeconds    pgtype.Int4
	PricePerSecond    pgtype.Int8
	PlayedAt          pgtype.Timestamptz
	Amount            int64
	Currency          string
	Meta              domain.JSONB
}

func (q *Queries) CreateDonationMessage(ctx context.Context, arg CreateDonationMessageParams) (DonationMessage, error) {
	row := q.db.QueryRow(ctx, createDonationMessage,
		arg.ID,
		arg.PayeeUserID,
		arg.PayerUserID,
		arg.PayerName,
		arg.Email,
		arg.Message,
		arg.MediaType,
		arg.MediaUrl,
		arg.MediaStartSeconds,
		arg.ChargedSeconds,
		arg.PricePerSecond,
		arg.PlayedAt,
		arg.Amount,
		arg.Currency,
		arg.Meta,
	)
	var i DonationMessage
	err := row.Scan(
		&i.ID,
		&i.PayeeUserID,
		&i.PayerUserID,
		&i.PayerName,
		&i.Email,
		&i.Message,
		&i.MediaType,
		&i.MediaUrl,
		&i.MediaStartSeconds,
		&i.ChargedSeconds,
		&i.PricePerSecond,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Meta,
		&i.PlayedAt,
		&i.CreatedAt,
	)
	return i, err
}
