// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  id,
  donation_message_id,
  payment_channel_id,
  payer_user_id,
  payee_user_id,
  gross_paid_amount,
  gateway_fee_fixed,
  gateway_fee_percentage_bps,
  gateway_fee_amount,
  platform_fee_fixed,
  platform_fee_percentage_bps,
  platform_fee_amount,
  fee_fixed,
  fee_percentage_bps,
  fee_amount,
  net_amount,
  currency,
  status,
  external_reference
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
) RETURNING id, donation_message_id, payment_channel_id, payer_user_id, payee_user_id, gross_paid_amount, gateway_fee_fixed, gateway_fee_percentage_bps, gateway_fee_amount, platform_fee_fixed, platform_fee_percentage_bps, platform_fee_amount, fee_fixed, fee_percentage_bps, fee_amount, net_amount, currency, status, external_reference, meta, created_at, paid_at, settled_at
`

type CreateTransactionParams struct {
	ID                       uuid.UUID
	DonationMessageID        uuid.UUID
	PaymentChannelID         int32
	PayerUserID              pgtype.UUID
	PayeeUserID              uuid.UUID
	GrossPaidAmount          int64
	GatewayFeeFixed          int64
	GatewayFeePercentageBps  int32
	GatewayFeeAmount         int64
	PlatformFeeFixed         int64
	PlatformFeePercentageBps int32
	PlatformFeeAmount        int64
	FeeFixed                 int64
	FeePercentageBps         int32
	FeeAmount                int64
	NetAmount                int64
	Currency                 string
	Status                   TransactionStatus
	ExternalReference        pgtype.Text
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.DonationMessageID,
		arg.PaymentChannelID,
		arg.PayerUserID,
		arg.PayeeUserID,
		arg.GrossPaidAmount,
		arg.GatewayFeeFixed,
		arg.GatewayFeePercentageBps,
		arg.GatewayFeeAmount,
		arg.PlatformFeeFixed,
		arg.PlatformFeePercentageBps,
		arg.PlatformFeeAmount,
		arg.FeeFixed,
		arg.FeePercentageBps,
		arg.FeeAmount,
		arg.NetAmount,
		arg.Currency,
		arg.Status,
		arg.ExternalReference,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.DonationMessageID,
		&i.PaymentChannelID,
		&i.PayerUserID,
		&i.PayeeUserID,
		&i.GrossPaidAmount,
		&i.GatewayFeeFixed,
		&i.GatewayFeePercentageBps,
		&i.GatewayFeeAmount,
		&i.PlatformFeeFixed,
		&i.PlatformFeePercentageBps,
		&i.PlatformFeeAmount,
		&i.FeeFixed,
		&i.FeePercentageBps,
		&i.FeeAmount,
		&i.NetAmount,
		&i.Currency,
		&i.Status,
		&i.ExternalReference,
		&i.Meta,
		&i.CreatedAt,
		&i.PaidAt,
		&i.SettledAt,
	)
	return i, err
}

const getTransactionByDonationMessageID = `-- name: GetTransactionByDonationMessageID :one
SELECT id, donation_message_id, payment_channel_id, payer_user_id, payee_user_id, gross_paid_amount, gateway_fee_fixed, gateway_fee_percentage_bps, gateway_fee_amount, platform_fee_fixed, platform_fee_percentage_bps, platform_fee_amount, fee_fixed, fee_percentage_bps, fee_amount, net_amount, currency, status, external_reference, meta, created_at, paid_at, settled_at FROM transactions WHERE donation_message_id = $1 LIMIT 1
`

func (q *Queries) GetTransactionByDonationMessageID(ctx context.Context, donationMessageID uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByDonationMessageID, donationMessageID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.DonationMessageID,
		&i.PaymentChannelID,
		&i.PayerUserID,
		&i.PayeeUserID,
		&i.GrossPaidAmount,
		&i.GatewayFeeFixed,
		&i.GatewayFeePercentageBps,
		&i.GatewayFeeAmount,
		&i.PlatformFeeFixed,
		&i.PlatformFeePercentageBps,
		&i.PlatformFeeAmount,
		&i.FeeFixed,
		&i.FeePercentageBps,
		&i.FeeAmount,
		&i.NetAmount,
		&i.Currency,
		&i.Status,
		&i.ExternalReference,
		&i.Meta,
		&i.CreatedAt,
		&i.PaidAt,
		&i.SettledAt,
	)
	return i, err
}

const getTransactionByExternalReference = `-- name: GetTransactionByExternalReference :one
SELECT id, donation_message_id, payment_channel_id, payer_user_id, payee_user_id, gross_paid_amount, gateway_fee_fixed, gateway_fee_percentage_bps, gateway_fee_amount, platform_fee_fixed, platform_fee_percentage_bps, platform_fee_amount, fee_fixed, fee_percentage_bps, fee_amount, net_amount, currency, status, external_reference, meta, created_at, paid_at, settled_at FROM transactions WHERE external_reference = $1 LIMIT 1
`

func (q *Queries) GetTransactionByExternalReference(ctx context.Context, externalReference pgtype.Text) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByExternalReference, externalReference)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.DonationMessageID,
		&i.PaymentChannelID,
		&i.PayerUserID,
		&i.PayeeUserID,
		&i.GrossPaidAmount,
		&i.GatewayFeeFixed,
		&i.GatewayFeePercentageBps,
		&i.GatewayFeeAmount,
		&i.PlatformFeeFixed,
		&i.PlatformFeePercentageBps,
		&i.PlatformFeeAmount,
		&i.FeeFixed,
		&i.FeePercentageBps,
		&i.FeeAmount,
		&i.NetAmount,
		&i.Currency,
		&i.Status,
		&i.ExternalReference,
		&i.Meta,
		&i.CreatedAt,
		&i.PaidAt,
		&i.SettledAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, donation_message_id, payment_channel_id, payer_user_id, payee_user_id, gross_paid_amount, gateway_fee_fixed, gateway_fee_percentage_bps, gateway_fee_amount, platform_fee_fixed, platform_fee_percentage_bps, platform_fee_amount, fee_fixed, fee_percentage_bps, fee_amount, net_amount, currency, status, external_reference, meta, created_at, paid_at, settled_at FROM transactions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.DonationMessageID,
		&i.PaymentChannelID,
		&i.PayerUserID,
		&i.PayeeUserID,
		&i.GrossPaidAmount,
		&i.GatewayFeeFixed,
		&i.GatewayFeePercentageBps,
		&i.GatewayFeeAmount,
		&i.PlatformFeeFixed,
		&i.PlatformFeePercentageBps,
		&i.PlatformFeeAmount,
		&i.FeeFixed,
		&i.FeePercentageBps,
		&i.FeeAmount,
		&i.NetAmount,
		&i.Currency,
		&i.Status,
		&i.ExternalReference,
		&i.Meta,
		&i.CreatedAt,
		&i.PaidAt,
		&i.SettledAt,
	)
	return i, err
}

const updateTransactionExternalReference = `-- name: UpdateTransactionExternalReference :exec
UPDATE transactions
SET external_reference = $2
WHERE id = $1
`

type UpdateTransactionExternalReferenceParams struct {
	ID                uuid.UUID
	ExternalReference pgtype.Text
}

func (q *Queries) UpdateTransactionExternalReference(ctx context.Context, arg UpdateTransactionExternalReferenceParams) error {
	_, err := q.db.Exec(ctx, updateTransactionExternalReference, arg.ID, arg.ExternalReference)
	return err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :exec
UPDATE transactions
SET status = $2
WHERE id = $1
`

type UpdateTransactionStatusParams struct {
	ID     uuid.UUID
	Status TransactionStatus
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransactionStatus, arg.ID, arg.Status)
	return err
}
