// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_fee_verrides.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getAllUserFeeOverridesByUserID = `-- name: GetAllUserFeeOverridesByUserID :many
SELECT id, user_id, payment_channel_id, platform_fee_fixed, platform_fee_percentage_bps FROM user_fee_overrides 
WHERE user_id = $1
`

func (q *Queries) GetAllUserFeeOverridesByUserID(ctx context.Context, userID uuid.UUID) ([]UserFeeOverride, error) {
	rows, err := q.db.Query(ctx, getAllUserFeeOverridesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserFeeOverride
	for rows.Next() {
		var i UserFeeOverride
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PaymentChannelID,
			&i.PlatformFeeFixed,
			&i.PlatformFeePercentageBps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFee = `-- name: GetUserFee :one
SELECT
    pc.id AS payment_channel_id,

    COALESCE(ufo.platform_fee_fixed, pc.platform_fee_fixed) 
        AS platform_fee_fixed,

    COALESCE(ufo.platform_fee_percentage_bps, pc.platform_fee_percentage_bps) 
        AS platform_fee_percentage_bps,

    pc.gateway_fee_fixed,
    pc.gateway_fee_percentage_bps

FROM payment_channels pc
LEFT JOIN user_fee_overrides ufo
    ON ufo.payment_channel_id = pc.id
    AND ufo.user_id = $1

WHERE pc.id = $2
LIMIT 1
`

type GetUserFeeParams struct {
	Userid           uuid.UUID
	Paymentchannelid int32
}

type GetUserFeeRow struct {
	PaymentChannelID         int32
	PlatformFeeFixed         int64
	PlatformFeePercentageBps int32
	GatewayFeeFixed          int64
	GatewayFeePercentageBps  int32
}

func (q *Queries) GetUserFee(ctx context.Context, arg GetUserFeeParams) (GetUserFeeRow, error) {
	row := q.db.QueryRow(ctx, getUserFee, arg.Userid, arg.Paymentchannelid)
	var i GetUserFeeRow
	err := row.Scan(
		&i.PaymentChannelID,
		&i.PlatformFeeFixed,
		&i.PlatformFeePercentageBps,
		&i.GatewayFeeFixed,
		&i.GatewayFeePercentageBps,
	)
	return i, err
}
