// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: donation_messages.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDonationMessage = `-- name: CreateDonationMessage :one
INSERT INTO donation_messages (
  id,
  payee_user_id,
  payer_user_id,
  payer_name,
  message,
  email,
  media_type,
  tts_language,
  tts_voice,
  media_provider,
  media_video_id,
  media_start_seconds,
  media_end_seconds,
  media_duration_seconds,
  played_at,
  meta
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, payee_user_id, payer_user_id, payer_name, message, email, media_type, tts_language, tts_voice, media_provider, media_video_id, media_start_seconds, media_end_seconds, media_duration_seconds, played_at, status, meta, created_at
`

type CreateDonationMessageParams struct {
	ID                   uuid.UUID
	PayeeUserID          uuid.UUID
	PayerUserID          pgtype.UUID
	PayerName            string
	Message              string
	Email                string
	MediaType            DonationMediaType
	TtsLanguage          pgtype.Text
	TtsVoice             pgtype.Text
	MediaProvider        NullMediaProvider
	MediaVideoID         pgtype.Text
	MediaStartSeconds    pgtype.Int4
	MediaEndSeconds      pgtype.Int4
	MediaDurationSeconds pgtype.Int4
	PlayedAt             pgtype.Timestamptz
	Meta                 []byte
}

func (q *Queries) CreateDonationMessage(ctx context.Context, arg CreateDonationMessageParams) (DonationMessage, error) {
	row := q.db.QueryRow(ctx, createDonationMessage,
		arg.ID,
		arg.PayeeUserID,
		arg.PayerUserID,
		arg.PayerName,
		arg.Message,
		arg.Email,
		arg.MediaType,
		arg.TtsLanguage,
		arg.TtsVoice,
		arg.MediaProvider,
		arg.MediaVideoID,
		arg.MediaStartSeconds,
		arg.MediaEndSeconds,
		arg.MediaDurationSeconds,
		arg.PlayedAt,
		arg.Meta,
	)
	var i DonationMessage
	err := row.Scan(
		&i.ID,
		&i.PayeeUserID,
		&i.PayerUserID,
		&i.PayerName,
		&i.Message,
		&i.Email,
		&i.MediaType,
		&i.TtsLanguage,
		&i.TtsVoice,
		&i.MediaProvider,
		&i.MediaVideoID,
		&i.MediaStartSeconds,
		&i.MediaEndSeconds,
		&i.MediaDurationSeconds,
		&i.PlayedAt,
		&i.Status,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}
